branches:
  only:
  - master
language: python
python:
- '3.6'
- '3.7'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: Vfs1U6IUhGcnJ6km/b09ewiAVPEVlLe8JLyoBXElA9fO3ShWjZFq4JGAxmAlh7S6duBH4A/owpSuToV/qTwdVMRxXYJQEQT59aWoDOyFrWKXZyM2kq3huII3Mdp3eH1i4ShRmzuveuv1O96yCoygkDwE/l5HXhZYLYlvhMKCnSX+Xf93ltDu8jQ5/subW9Kv2Ia7cgX7A3EPNqqKDX2AxkNkg3vxpPX2rbb6Xt4mG4rPWNY1wIwx0Uda+G+XrN+w63tlLC8ih3gOS9ORMiw8UrGMr9BGMxHbYXrsTRGHtIYnv6Uko3LbLOdlPnTAZmhzMeLLh0vBjEmxLy0zJ2f1s29hDR1JxTp6ecBBLMyGrtAw5jDVV5CfHIlKM7yKM78xNY55i9FudgqfxteLfTZdNTyzGNdG71fEPcMTPLhUiHXeJBYCHKd1wdEya5OvS59mRBeSwUk7dlRv/VgfuYAh6csqFwjpLBljnyM/hpK/LnKPRVDg4bYh65kJR0ggC4cJEMPCvOgGwdBuN7+n4/SdCvXfYkgg2B/XPfxABPvNX6Y3l1wC/lg+stS2rxe/243CPy4yYzeZCSXDu1gWT/6zuxQDbapXkbINtSeNjdCty1vqRhPFIDN6apotigndTjU5JCdxNd5AED/ZLbzjK69XIPnsOz0CFvK6DMOSnfVrfsM=
