branches:
  only:
  - master
language: python
python:
- '3.6'
- '3.7''
- '3.8'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: ryftx1pCi67BsZ4YvUyxlcRKZzfpO9vhnTmCdsL4xdwSyUl6tf48WWa07S8WxtZ066n9A9afs9+NT6ndpJiR71aqxuL6hC3Hd4CgIeVvclbNts/70S6qbCUH2VWahqz7NIJbHdVDJkB64fJgfiUJn1TtJyH6d3k7A7OqWI2amfOkEkDUB1cPYc05+qmhp57zmMPO7hqlSrATSC939T/v0txGxoEGWQdv8LB+eT9fJC1nOHQ9laTAnIVUrALT9N1XKMvW40Ec3UJEgxc8xDrHAEJp7nH81gSK7PaJWnu3+P5Eq9Gnp/0T4aEjKa3nbdX8x65F1FO6HaWN5+RqgDG6Jr+TdDVeTG8yB4uqKd8WU19gsNe9N2r7mcYhkwyDIyWUzIorJkhJpK4Gs8oMk1gpKjmL4M3nuuq4Xm0+PbpSejRC+8MkMmX8WK76UpdG6Qv+fTawCJ5zAh54qJgeQw6BGtCHaPhu12Hw6ckukPgxCTHUQlpQ8G1cTnmSno0NOyCgrct8jQRW+dr+g5huvYRt/tapBudDQ0MU7064yCsM2LFlISVzavKPJXppwJh9RzbjvInV2GMdGQbE6OvVEYE3SPlycvniZf+gD3uheW4spvQmV4/uTFAXToI+Mxt9NEaJVUrq3lPetiNVrEbdMeY0cGD3tu5mVwqnX6D5xi2Frk8=
