apiVersion: v1
kind: Service
metadata:
  name: os-vim-driver
  labels:
    app: os-vim-driver
spec:
  type: {{ .Values.service.type }}
  ports:
{{- if .Values.app.config.security.ssl.enabled }}
  - port: 8392
    targetPort: 8392
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: https
{{- else }}
  - port: 8292
    targetPort: 8292
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
{{- end }}
  selector:
    app: os-vim-driver
