heat_template_version: 2013-05-23

description: >
  Basic example to deploy a single Compute instance

parameters:
  key_name:
    type: string
  image:
    type: string
  flavor:
    type: string
  network:
    type: string
resources:
  hello_world_server:
    type: OS::Nova::Server
    properties:
      flavor:
        get_param: flavor
      user_data_format: SOFTWARE_CONFIG
      image:
        get_param: image
      key_name:
        get_param: key_name
      networks:
      - port: { get_resource: hello_world_server_port }
  hello_world_server_port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}
outputs:
  private_ip:
    value:
      get_attr:
      - hello_world_server
      - networks
      - private
      - 0
    description: The private IP address of the hello_world_server
