name: os-vim-driver
version: 2.1.0a3
appVersion: 2.1.0a3
apiVersion: v1
description: A Helm chart for the Openstack VIM Driver
keywords:
- OSS
- LM
- Resource Manager
- Brent
- Openstack
- VIM
- Accanto
engine: gotpl
